User_name = input("what is your name")
print(User_name)
User_hobby = input("what is your favoritr hobby?")
print(User_hobby)
User_city = input("what is your current city?")
print(User_city)
print("Hello"+ User_name)
print(User_name +"love to"+User_hobby in + User_city)